### PR TITLE
Ability to locate translations during development on CentOS 7

### PR DESCRIPTION
**Pull request by mattias-p**
This mimics how we do it in Engine.

This makes the development workflow nicer on CentOS 7. I don't develop on CentOS 7 on a daily basis, but sometimes I do. Like when there's a CentOS 7 specific behavior I need to tackle.

I don't get why Travis fails on this. I'll have to get back to that later.

### CODE REVIEW

**Comment by sandoche2k** [comment]
@mattias-p it is  not clear the usage of this PR

**Review by matsduf — APPROVED** [review]

**Comment by mattias-p** [comment]
@sandoche2k This is useful when you're using CentOS 7 for your development environment.

**Comment by matsduf** [comment]
@sandoche2k, can you review this?

**Review by sandoche2k — APPROVED** [review]

**Comment by sandoche2k** [comment]
@mattias-p after checking the reason for travis failure.. can you merge?

**Comment by sandoche2k** [comment]
@mattias-p merge?

**Comment by matsduf** [comment]
@mattias-p, can this be merged?

**Comment by mattias-p** [comment]
No, Travis is failing. It can't be merged in this condition. I'd like to fix it but I'm having some troubles. Since this isn't so important anyway maybe I should just give up on it. If it does become important later on I'll put in the effort to fix it then.

**Pull request closed without merging**
