### PR TITLE
Zonemaster-CLI: merge master into develop

### PR DESCRIPTION
**Pull request by matsduf**
Something has been merged into master instead of develop in Octorber last year. To correct that, merge master into develop.

When this has been merged, a new PR will be created to reintroduce the Danish translations into the develop branch.

### CODE REVIEW

**Comment by matsduf** [comment]
> @matsduf Is it correct that you have an English version in the da.po file?

No, and that should be corrected. I think it will be easier to do in two steps. First correct, and then add a change to the develop branch.

**Comment by mattias-p** [comment]
I don't mean to be adverse but I have a couple of points to make here.

First, we should strive to always keep develop in a releasable state. In this case that could be achieved by creating a new local branch off of master, cherry picking the reverted commits back onto the new branch and merging all of that back into develop in a single PR.

Second, this operation is not according to our processes. Our current process is to only merge develop into master and not the other way around. I don't see much of a point in merging master back into develop in an ad-hoc manner. That said, if we do want to merge master back into develop, we should update the release process with a merge-back-into-develop step and perform that merge on all the repos.

N.B. The merge-back-into-develop step could include an instruction to reapply any commits that were reverted on the master branch.

**Comment by matsduf** [comment]
> First, we should strive to always keep develop in a releasable state. In this case that could be achieved by creating a new local branch off of master, cherry picking the reverted commits back onto the new branch and merging all of that back into develop in a single PR.

The develop branch is in releasable state. We did the release from the develop branch. This will be an update to the develop branch, and if you want to do it some other way, please create a pull request.

> Second, this operation is not according to our processes. Our current process is to only merge develop into master and not the other way around. I don't see much of a point in merging master back into develop in an ad-hoc manner. 

This would not be the first time merging master into develop. I have created such a pull request before on your proposal.

> That said, if we do want to merge master back into develop, we should update the release process with a merge-back-into-develop step and perform that merge on all the repos.

Fine for me. I have checked all repos and this is the only repo where such an operation would do any change to any file. But changing the release process is not part of this pull request.

> N.B. The merge-back-into-develop step could include an instruction to reapply any commits that were reverted on the master branch.

That comment is not for this pull request, is it?

**Comment by mattias-p** [comment]
> > First, we should strive to always keep develop in a releasable state. In this case that could be achieved by creating a new local branch off of master, cherry picking the reverted commits back onto the new branch and merging all of that back into develop in a single PR.
> 
> The develop branch is in releasable state. We did the release from the develop branch. This will be an update to the develop branch, and if you want to do it some other way, please create a pull request.

Okay, I'll do that.

> > That said, if we do want to merge master back into develop, we should update the release process with a merge-back-into-develop step and perform that merge on all the repos.
> 
> Fine for me. I have checked all repos and this is the only repo where such an operation would do any change to any file. But changing the release process is not part of this pull request.

I'll create a PR for an update to the release process.

> > N.B. The merge-back-into-develop step could include an instruction to reapply any commits that were reverted on the master branch.
> 
> That comment is not for this pull request, is it?

Correct.

**Comment by matsduf** [comment]
@sandoche2k and @mattias-p, how do you want to fix the issue? As it is now, the package on CPAN is different in one file from master branch.

**Comment by mattias-p** [comment]
I made an alternative proposal in #142.

**Comment by matsduf** [comment]
Replaced by #142.

**Pull request closed without merging**
