### PR TITLE
Profiles feature branch in CLI

### PR DESCRIPTION
**Pull request by mattias-p**
This is a work in progress for #72.

### CODE REVIEW

**Comment by sandoche2k** [comment]
Need one more approval to accept the PR

**Comment by sandoche2k** [comment]
@mattias-p please merge

**Comment by mattias-p** [comment]
At this points the `profiles` branch contains only documentation. When the implementation is made, its PR should target the `profiles` branch. Once the implementation has been merged into the `profiles` branch, the entire profiles feature with both documentation and implementation can be merged into the develop branch (preferably using this PR).

**Comment by sandoche2k** [comment]
@mattias-p can this PR be merged?

**Comment by sandoche2k** [comment]
@mattias-p pls. merge

**Comment by mattias-p** [comment]
@sandoche2k As soon as zonemaster/zonemaster-engine#386 is merged.

**Comment by sandoche2k** [comment]
@mattias-p merge?

**Pull request merged**
